Changes
OkemmaduNancy/ReactJS pull request #3
Opened 2021-06-17 11:24 UTC by OkemmaduNancy

2021-06-17 14:50 UTC, EngrEric commented on src/APIs.js
>                  { this.state.newData.map((item, index) => <h1 key={index}>{item.price}</h1>)}
new data is not verbose. Give your variable names with meaning for easy readability of codes

2021-06-17 14:51 UTC, EngrEric commented on src/App.js
>      ProductData: ProductData,
variable names starts with small letter, i.e camel case

2021-06-17 14:51 UTC, EngrEric commented on src/App.js
why the space here

2021-06-17 14:52 UTC, EngrEric commented on src/Component/AboutUs.js
> +      <button onClick={() => history.push("/App")} className={classes.readMoreButton}>Read More</button>
route names should start with small letters and separated by hyphens

2021-06-17 14:53 UTC, EngrEric commented on src/Component/Card.js
> +
why space here

2021-06-17 14:54 UTC, EngrEric commented on src/Component/Card.module.css
> +} */
remove is you're not using it

2021-06-17 14:55 UTC, EngrEric commented on src/Component/Home.js
> +          <a href="sign-up">Sign Up</a>
`href="/sign-up"` notice the difference

2021-06-17 14:55 UTC, EngrEric commented on src/Component/Nav/Burger.js
> +`
why the space here

2021-06-17 14:55 UTC, EngrEric commented on src/Component/Nav/Burger.js
> +
remove

2021-06-17 14:55 UTC, EngrEric commented on src/Component/Nav/Burger.js
> +                <div />
why empty divs

2021-06-17 14:56 UTC, EngrEric commented on src/Component/Nav/RightNav.js
> +
space here, remove

2021-06-17 14:56 UTC, EngrEric commented on src/Component/Nav/RightNav.js
> +
space here, remove

2021-06-17 14:57 UTC, EngrEric commented on src/Component/ProductDetails.js
> +const ProductDetails = () => {
add space btw import and component declaration

2021-06-17 14:57 UTC, EngrEric commented on src/Component/ProductDetails.js
> +
one space is okay here

2021-06-17 15:01 UTC, EngrEric commented on src/Component/ProductDetails.js
>              const details = await fetch(`http://localhost:4000/v1/product/${id}`, {
create a base use url  in constants.js and import here

//constants.js
`export BASR_URL = 'http://localhost:4000/v1'`

then import here and use as follows
` await fetch(`${BASR_URL }/product/${id}`,`

this way you  can use BASE_URL so many places. Also notice how i named my  constant string variable in upper case

2021-06-17 15:02 UTC, EngrEric commented on src/Component/ProductDetails.js
> +    console.log(productDetails);
remove console after use. don't push for production

2021-06-17 15:02 UTC, EngrEric commented on src/Component/ProductDetails.js
> +    console.log(productDetails);
remove console after use. don't push for production

2021-06-17 15:02 UTC, EngrEric commented on src/Component/ProductDetails.js
> +
remove space

2021-06-17 15:03 UTC, EngrEric commented on src/Component/ProductDetails.module.css
> +
remove space

2021-06-17 15:03 UTC, EngrEric commented on src/Component/ProductDetails.module.css
> +
remove space

2021-06-17 15:04 UTC, EngrEric commented on src/Component/SignUp.js
> +  const [job, setJob] = useState("");
rewrite all these, 
`const [userInputs, setUserInputs] = useState({})`

2021-06-17 15:05 UTC, EngrEric commented on src/Component/SignUp.js
> +    }
remove

2021-06-17 15:06 UTC, EngrEric commented on src/Component/SignUp.js
> +    console.log(user);
`console.log(userInput)` will give you all the details

2021-06-17 15:08 UTC, EngrEric commented on src/Component/SignUp.js
> +  };
remove all the handle this and that. Replace with one function for all the inputs except confirm password

```
const handleInputChange = (event) => {
const name = event.target.name
const value = event.target.value
setUserInput({ ...userInput, [name]: value})
```

2021-06-17 15:09 UTC, EngrEric commented on src/Component/SignUp.js
> +
remove

2021-06-17 15:11 UTC, EngrEric commented on src/Component/SignUp.js
> +          Email:
replae al handle functions for input to `handleInputChange `

2021-06-17 15:21 UTC, EngrEric commented on src/Component/SignUp.module.css
> +
remove space

2021-06-17 15:21 UTC, EngrEric commented on src/Component/SignUp.module.css
> +
remove space

2021-06-17 15:22 UTC, EngrEric commented on src/Component/SignUp.module.css
> +i{
give space

2021-06-17 15:22 UTC, EngrEric commented on src/Component/Store.js
> +
space is much

2021-06-17 15:22 UTC, EngrEric commented on src/Form/Form.js
> -                    <br />
not aligned

2021-06-17 15:23 UTC, EngrEric commented on src/Form/Form.js
>          </div>
align properly

2021-06-17 15:23 UTC, EngrEric commented on src/Form/form.module.css
> +input:hover {
remove all commented codes

2021-06-17 15:24 UTC, EngrEric commented on src/Router.js
>            <Switch>
replace this `<h1>loading</h1>`to a loading component, maybe spinning one

2021-06-17 15:24 UTC, EngrEric requested changes
You need to make the changes from the comments

2021-06-18 07:25 UTC, OkemmaduNancy commented on src/Component/Nav/Burger.js
> +                <div />
for creating a hamburger

2021-06-24 11:47 UTC, merged